# Generated by Django 5.0.3 on 2026-03-13 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('guest_count', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('BUFFET', 'Buffet'), ('TABLE_SERVICE', 'Table Service'), ('DELIVERY', 'Delivery')], max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('menu_locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['event_date', 'status'], name='events_event_d_0b0e32_idx')],
            },
        ),
    ]
