# Generated by Django 5.0.3 on 2026-03-13 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dish_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('unit_type_snapshot', models.CharField(blank=True, max_length=10)),
                ('recipe_snapshot', models.JSONField(blank=True, default=list)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_appearances', to='master.dish')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='events.event')),
            ],
            options={
                'db_table': 'event_menu_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
