# Generated by Django 5.0.3 on 2026-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='guest_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
