# Generated by Django 5.0.3 on 2026-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
