# Generated by Django 5.0.3 on 2026-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_add_estimated_budget_to_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=15),
        ),
    ]
