# Generated by Django 5.0.3 on 2026-03-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='events.event')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_totals', to='master.ingredient')),
            ],
            options={
                'db_table': 'event_ingredients',
                'indexes': [models.Index(fields=['event', 'category'], name='event_ingre_event_i_d1d95d_idx')],
                'unique_together': {('event', 'ingredient')},
            },
        ),
    ]
