# Generated by Django 5.0.3 on 2026-03-13 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('PLATE', 'Plate'), ('KG', 'Kilogram'), ('PIECE', 'Piece'), ('LITRE', 'Litre'), ('PORTION', 'Portion')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('has_recipe', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('GROCERY', 'Grocery'), ('VEGETABLE', 'Vegetable'), ('MEAT', 'Meat'), ('FRUIT', 'Fruit'), ('DISPOSABLE', 'Disposable'), ('RENTAL', 'Rental'), ('OTHER', 'Other')], max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Piece')], max_length=10)),
                ('base_qty_ref', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='master.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='master.ingredient')),
            ],
            options={
                'db_table': 'dish_recipes',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
    ]
